---
- name: Install docker from official source
  shell: curl -sSL https://get.docker.com/ | sh
  sudo: True

- name: Add user ubuntu to the docker group 
  user:
    name: ubuntu
    groups: docker,
    append: True
  sudo: True